// This file is automatically generated.
// Do not edit it
// open gen_param_struct.py, edit struct definition and run it to generate new file
const int32_t OnboardParamCount = 22;

/*
 * variable array of parameters in RAM
 */ 
static floatint gp_val[22];

/**
 *
 */ 
const GlobalParam_t GlobalParam[] = {
{"SYS_ID", {.u32 = 1}, {.u32 = 20}, {.u32 = 255}, &gp_val[0], NULL, MAVLINK_TYPE_UINT32_T, "System ID.\n This value MUST BE FIRST in param structure. Value 0 reserved for ground station."},
{"SYS_mavtype", {.u32 = 0}, {.u32 = 10}, {.u32 = 16}, &gp_val[1], NULL, MAVLINK_TYPE_UINT32_T, "Autopilot type (0 - generic, 1 - fixed wing, 10 - ground rover).\nOther types you can found in enum MAV_TYPE \nNOTE! You MUST REBOOT device after changing it."},
{"SH_enable", {.u32 = 0}, {.u32 = 0}, {.u32 = 1}, &gp_val[2], NULL, MAVLINK_TYPE_UINT32_T, "Set to 1 to switch off telemetry sending and enabling shell."},
{"T_raw_imu", {.u32 = 1}, {.u32 = 0}, {.u32 = 86400000}, &gp_val[3], &_sendtmo_param_checker, MAVLINK_TYPE_UINT32_T, "Interval of sending this data in milliseconds.\nSet it to 0 for disabling"},
{"T_raw_press", {.u32 = 1}, {.u32 = 0}, {.u32 = 86400000}, &gp_val[4], &_sendtmo_param_checker, MAVLINK_TYPE_UINT32_T, "Timeout help here"},
{"T_scal_imu", {.u32 = 1}, {.u32 = 0}, {.u32 = 86400000}, &gp_val[5], &_sendtmo_param_checker, MAVLINK_TYPE_UINT32_T, NULL},
{"T_scal_press", {.u32 = 1}, {.u32 = 0}, {.u32 = 86400000}, &gp_val[6], &_sendtmo_param_checker, MAVLINK_TYPE_UINT32_T, NULL},
{"T_attitude", {.u32 = 1}, {.u32 = 0}, {.u32 = 86400000}, &gp_val[7], &_sendtmo_param_checker, MAVLINK_TYPE_UINT32_T, NULL},
{"T_vfr_hud", {.u32 = 1}, {.u32 = 0}, {.u32 = 86400000}, &gp_val[8], &_sendtmo_param_checker, MAVLINK_TYPE_UINT32_T, NULL},
{"T_gps_int", {.u32 = 1}, {.u32 = 0}, {.u32 = 86400000}, &gp_val[9], &_sendtmo_param_checker, MAVLINK_TYPE_UINT32_T, NULL},
{"T_sys_status", {.u32 = 1}, {.u32 = 0}, {.u32 = 86400000}, &gp_val[10], &_sendtmo_param_checker, MAVLINK_TYPE_UINT32_T, NULL},
{"T_position_ned", {.u32 = 1}, {.u32 = 0}, {.u32 = 86400000}, &gp_val[11], &_sendtmo_param_checker, MAVLINK_TYPE_UINT32_T, NULL},
{"T_nav_output", {.u32 = 1}, {.u32 = 0}, {.u32 = 86400000}, &gp_val[12], &_sendtmo_param_checker, MAVLINK_TYPE_UINT32_T, NULL},
{"T_reserved2", {.u32 = 1}, {.u32 = 0}, {.u32 = 86400000}, &gp_val[13], &_sendtmo_param_checker, MAVLINK_TYPE_UINT32_T, NULL},
{"T_reserved3", {.u32 = 1}, {.u32 = 0}, {.u32 = 86400000}, &gp_val[14], &_sendtmo_param_checker, MAVLINK_TYPE_UINT32_T, NULL},
{"T_reserved4", {.u32 = 1}, {.u32 = 0}, {.u32 = 86400000}, &gp_val[15], &_sendtmo_param_checker, MAVLINK_TYPE_UINT32_T, NULL},
{"T_reserved5", {.u32 = 1}, {.u32 = 0}, {.u32 = 86400000}, &gp_val[16], &_sendtmo_param_checker, MAVLINK_TYPE_UINT32_T, NULL},
{"T_reserved6", {.u32 = 1}, {.u32 = 0}, {.u32 = 86400000}, &gp_val[17], &_sendtmo_param_checker, MAVLINK_TYPE_UINT32_T, NULL},
{"DBG_reserved0", {.u32 = 0}, {.u32 = 0}, {.u32 = 10000}, &gp_val[18], NULL, MAVLINK_TYPE_UINT32_T, NULL},
{"DBG_reserved1", {.u32 = 0}, {.u32 = 0}, {.u32 = 10000}, &gp_val[19], NULL, MAVLINK_TYPE_UINT32_T, NULL},
{"DBG_reserved2", {.u32 = 0}, {.u32 = 0}, {.u32 = 10000}, &gp_val[20], NULL, MAVLINK_TYPE_UINT32_T, NULL},
{"param_end_mark", {.u32 = 0}, {.u32 = 0}, {.u32 = 1224}, &gp_val[21], NULL, MAVLINK_TYPE_UINT32_T, "Fake parameter with maximum allowable name length"},
};
