# имя главного файла без расширения
document := KCAY.469555.025pe3

TOP_DIR = ../../../..

include $(TOP_DIR)/include.mak

semiall: pdf archive 

semiallbw: archivebw 

$(document).tex: pe3_table.tex 


