# имя главного файла без расширения
document := KCAY.468352.006ps


TOP_DIR = ../../../..
include $(TOP_DIR)/include.mak


semiall: pdf archive reading hyperref distrib booklet 

# черно-белый вариант документации для репликатора нет смысла собирать
# но правило должно быть, чтобы не возникало ошибок
# при сборке всего набора с целью allbw

semiallbw: archivebw distribbw bookletbw


